import Head from 'next/head'
import BringingBanner from '../components/BringingBanner'
import Categories from '../components/Categories'
import Banner from '../components/Category/Banner'
import Hero from '../components/Category/Hero'
import Footer from '../components/Footer'
import Header from '../components/Header'

const earphones = ({ result }) => {
  return (
    <div className='font-main'>
        <Head>
            <title>Audiophile | Speakers</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <div className='bg-black pb-3' >
        <div className='bg-white/30 h-[1px]  w-[95%] md:w-[85%] mx-auto  ' />
        </div>
        <Hero title='earphones' />
        <Banner 
            img={'https://audiophile-gamma.vercel.app/assets/product-yx1-earphones/desktop/image-product.jpg'}
            title={'YX1 Wireless Earphones'}
            text={'Tailor your listening experience with bespoke dynamic drivers from the new YX1 Wireless Earphones. Enjoy incredible high-fidelity sound even in noisy environments with its active noise cancellation feature.'}
            slug={result[0].slug}
        />
        <Categories />
        <BringingBanner />
        <Footer />
    </div>
  )
}

export default earphones

export async function getServerSideProps() {
  const data = await fetch('https://jsonkeeper.com/b/S9OG').then(res => res.json())

  const result = data.filter((product) => product.category === "earphones") 

  return {
      props: {
          result,
      }
  } 
}